from datetime import datetime #voor 'date'


from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


#tabel creëren met bijhorende kolommen
class Material(db.Model):
    material_id = db.Column(db.Integer, primary_key=True) #GENERATED BY DEFAULT AS IDENTITY (SQL)
    material_type = db.Column(db.String, nullable=False) #String ipv. text (SQL)
    description = db.Column(db.String, nullable=False)
    brand = db.Column(db.String, nullable=False)
    price = db.Column(db.Float) #Float ipv. Numeric (SQL)
    lifecycle = db.Column(db.String)

    #contraints toevoegen
    __table_args__ = (
        db.UniqueConstraint('material_type', 'description', name='UC1'),
        )

    #zodat navigatie mogelijk: van Material → naar alle Items (EN) van Item → terug naar Material
    #lazy=True: SQLAlchemy laadt de lijst pas wanneer je ernaar vraagt
    items = db.relationship('Item', backref='material', lazy=True)

    #bepaalt hoe het object wordt weergegeven als tekst (handig bij debuggen)
    def __repr__(self):
        return f"<Material ID={self.material_id}, type={self.material_type}>" #geen 'description' want vaak te lang


class Zone(db.Model):
    zone_name = db.Column(db.String(3), primary_key=True)

    items = db.relationship('Item', backref='zone', lazy=True)

    def __repr__(self):
        return f'<zone {self.zone_name}>'


class Item(db.Model):
    item_id = db.Column(db.Integer, primary_key=True) #GENERATED BY DEFAULT AS IDENTITY (SQL)
    material_id = db.Column(db.Integer, db.ForeignKey('material.material_id', ondelete="CASCADE", onupdate="CASCADE"), nullable=False)
    zone_name = db.Column(db.String(3), db.ForeignKey('zone.zone_name', ondelete="CASCADE", onupdate="CASCADE"), nullable=False)
    purpose = db.Column(db.String, nullable=False)
    packaging = db.Column(db.String, nullable=False)
    quantity = db.Column(db.Integer, nullable=False)
    comment = db.Column(db.String)

    __table_args__ = (
        db.UniqueConstraint('material_id', 'zone_name', 'purpose', 'packaging', name='UC2'),
        db.CheckConstraint("purpose IN ('keep', 'sell', 'dispose')", name='CC2'),
        db.CheckConstraint("packaging IN ('open', 'closed', 'none')", name='CC3'),
    )

    reservations = db.relationship('Reservation', backref='item', lazy=True)

    def __repr__(self):
        return f"<Item ID={self.item_id}, material={self.material_id}, zone={self.zone_name}>"


class Reservation(db.Model):
    item_id = db.Column(db.Integer, db.ForeignKey('item.item_id', ondelete="CASCADE", onupdate="CASCADE"), primary_key=True)
    username = db.Column(db.String, primary_key=True)
    date = db.Column(db.DateTime, server_default=db.func.current_timestamp(), primary_key=True) #timestamp DEFAULT CURRENT_TIMESTAMP (SQL)
    quantity = db.Column(db.Integer, nullable=False)
    project = db.Column(db.String)

    #geen relationship nodig, want we navigeren al van item → reservation

    def __repr__(self):
        return f"<Reservation: item={self.item_id}, user={self.username}, date={self.date}>" #PK