from datetime import datetime #voor 'date'


from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()


#tabel creëren met bijhorende kolommen
class Company(db.Model):
    company_name = db.Column(db.String, primary_key=True) #String ipv. text (SQL)

    #zodat navigatie langs 2 kanten mogelijk is
    #lazy=True: SQLAlchemy laadt de lijst pas wanneer je ernaar vraagt
    materials = db.relationship('Material', backref='company', lazy=True) #Material ook eigen aan company!
    users = db.relationship('User', backref='company', lazy=True)
    zones = db.relationship('Zone', backref='company', lazy=True)

    #bepaalt hoe het object wordt weergegeven als tekst (handig bij debuggen)
    def __repr__(self):
        return f"<Company: {self.company_name}>"


class User(db.Model):
    __tablename__ = 'app_user' # 'user' is een gereserveerd woord in SQL

    username = db.Column(db.String, primary_key=True)
    password = db.Column(db.String, nullable=False)
    company_name = db.Column(db.String, db.ForeignKey('company.company_name', ondelete="CASCADE", onupdate="CASCADE"),nullable=False)

    reservations = db.relationship('Reservation', backref='user', lazy=True)

    def __repr__(self):
        return f"<User {self.username}, from company {self.company_name}>"


class Material(db.Model):
    material_id = db.Column(db.Integer, primary_key=True) #GENERATED BY DEFAULT AS IDENTITY (SQL)
    material_type = db.Column(db.String, nullable=False)
    description = db.Column(db.String, nullable=False)
    brand = db.Column(db.String, nullable=False)
    price = db.Column(db.Float) #Float ipv. Numeric (SQL)
    lifecycle = db.Column(db.String)
    company_name = db.Column(db.String, db.ForeignKey('company.company_name', ondelete="CASCADE", onupdate="CASCADE"), nullable=False)

    #contraints toevoegen
    __table_args__ = (
        db.UniqueConstraint('company_name','material_type', 'description', name='UC1'), #zelfde materiaal mag bij ander bedrijf opnieuw bestaan
        )

    items = db.relationship('Item', backref='material', lazy=True)

    def __repr__(self):
        return f"<Material_ID= {self.material_id}, type= {self.material_type}>" #geen 'description' want vaak te lang


class Zone(db.Model):

    zone_id = db.Column(db.Integer, primary_key=True)  # GENERATED BY DEFAULT AS IDENTITY (SQL)
    zone_name = db.Column(db.String(3), nullable=False)
    company_name = db.Column(db.String, db.ForeignKey('company.company_name', ondelete="CASCADE", onupdate="CASCADE"), nullable=False)

    __table_args__ = (
        db.UniqueConstraint('company_name', 'zone_name', name='UC2'),
    )

    items = db.relationship('Item', backref='zone', lazy=True)

    def __repr__(self):
        return f'<zone {self.zone_name}>'


class Item(db.Model):
    item_id = db.Column(db.Integer, primary_key=True) #GENERATED BY DEFAULT AS IDENTITY (SQL)
    material_id = db.Column(db.Integer, db.ForeignKey('material.material_id', ondelete="CASCADE", onupdate="CASCADE"), nullable=False)
    zone_id = db.Column(db.Integer, db.ForeignKey('zone.zone_id', ondelete="CASCADE", onupdate="CASCADE"), nullable=False)
    purpose = db.Column(db.String, nullable=False)
    packaging = db.Column(db.String, nullable=False)
    quantity = db.Column(db.Integer, nullable=False)
    comment = db.Column(db.String)

    __table_args__ = (
        db.UniqueConstraint('material_id', 'zone_id', 'purpose', 'packaging', name='UC3'),
        db.CheckConstraint("purpose IN ('keep', 'sell', 'dispose')", name='CC2'),
        db.CheckConstraint("packaging IN ('open', 'closed', 'none')", name='CC3'),
    )

    reservations = db.relationship('Reservation', backref='item', lazy=True)

    def __repr__(self):
        return f"<Item_ID={self.item_id}, material_ID={self.material_id}, zone={self.zone.zone_name}>"


class Reservation(db.Model):
    item_id = db.Column(db.Integer, db.ForeignKey('item.item_id', ondelete="CASCADE", onupdate="CASCADE"), primary_key=True)
    username = db.Column(db.String, db.ForeignKey('app_user.username', ondelete="CASCADE", onupdate="CASCADE"), primary_key=True)
    date = db.Column(db.DateTime, server_default=db.func.current_timestamp(), primary_key=True) #timestamp DEFAULT CURRENT_TIMESTAMP (SQL)
    quantity = db.Column(db.Integer, nullable=False)
    project = db.Column(db.String)

    #geen relationship nodig, want we navigeren al van item → reservation

    def __repr__(self):
        return f"<Reservation: Item_ID={self.item_id} by {self.username} on {self.date}>" #PK