"""fix aantal default and not null

Revision ID: 311af5c3882c
Revises: de2756a42d4c
Create Date: 2025-11-02 16:43:59.091158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '311af5c3882c'
down_revision = 'de2756a42d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('aantal',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('comment',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('materiaal', schema=None) as batch_op:
        batch_op.alter_column('prijs',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('materiaal', schema=None) as batch_op:
        batch_op.alter_column('prijs',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)

    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('aantal',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
