"""FULL REBUILD: new models

Revision ID: 9bcf13106938
Revises: 
Create Date: 2025-11-21 21:45:12.937728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bcf13106938'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('lifecycle', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('material_id'),
    sa.UniqueConstraint('material_type', 'description', name='UC1')
    )
    op.create_table('zone',
    sa.Column('zone_name', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('zone_name')
    )
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=3), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('packaging', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.CheckConstraint("packaging IN ('open', 'closed', 'none')", name='CC3'),
    sa.CheckConstraint("purpose IN ('keep', 'sell', 'dispose')", name='CC2'),
    sa.ForeignKeyConstraint(['material_id'], ['material.material_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_name'], ['zone.zone_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('material_id', 'zone_name', 'purpose', 'packaging', name='UC2')
    )
    op.create_table('reservation',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'username', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('item')
    op.drop_table('zone')
    op.drop_table('material')
    # ### end Alembic commands ###
