"""FULL REBUILD: new models

Revision ID: cac9dcc9c63b
Revises: 
Create Date: 2025-11-27 15:38:55.054394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac9dcc9c63b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('company_name')
    )
    op.create_table('app_user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('material',
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('material_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('lifecycle', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_id'),
    sa.UniqueConstraint('company_name', 'material_type', 'description', name='UC1')
    )
    op.create_table('zone',
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=3), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_name'], ['company.company_name'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('zone_id'),
    sa.UniqueConstraint('company_name', 'zone_name', name='UC2')
    )
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('packaging', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.CheckConstraint("packaging IN ('open', 'closed', 'none')", name='CC3'),
    sa.CheckConstraint("purpose IN ('keep', 'sell', 'dispose')", name='CC2'),
    sa.ForeignKeyConstraint(['material_id'], ['material.material_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['zone.zone_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('material_id', 'zone_id', 'purpose', 'packaging', name='UC3')
    )
    op.create_table('reservation',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username'], ['app_user.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'username', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('item')
    op.drop_table('zone')
    op.drop_table('material')
    op.drop_table('app_user')
    op.drop_table('company')
    # ### end Alembic commands ###
