"""Add is_changed field to Item model

Revision ID: cd7f72cd95d4
Revises: 7eb53a8fc380
Create Date: 2025-12-15 15:28:34.653541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd7f72cd95d4'
down_revision = '7eb53a8fc380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_changed', sa.Boolean(), nullable=True, server_default=sa.false()))
    
    # Set default value for existing rows (in case server_default doesn't work)
    op.execute("UPDATE item SET is_changed = FALSE WHERE is_changed IS NULL")
    
    # Now make it non-nullable
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('is_changed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('is_changed')

    # ### end Alembic commands ###
