"""Initial migration: create tables

Revision ID: de2756a42d4c
Revises: 
Create Date: 2025-11-02 15:41:57.636898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2756a42d4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifecycle',
    sa.Column('lifecycle', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('lifecycle')
    )
    op.create_table('zone',
    sa.Column('zone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('zone')
    )
    op.create_table('materiaal',
    sa.Column('materiaal_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('omschrijving', sa.String(), nullable=False),
    sa.Column('lifecycle', sa.String(), nullable=True),
    sa.Column('merk', sa.String(), nullable=False),
    sa.Column('prijs', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['lifecycle'], ['lifecycle.lifecycle'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('materiaal_id'),
    sa.UniqueConstraint('type', 'omschrijving', name='UC1')
    )
    op.create_table('item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('materiaal_id', sa.Integer(), nullable=False),
    sa.Column('zone', sa.String(), nullable=False),
    sa.Column('doel', sa.String(), nullable=False),
    sa.Column('verpakking', sa.String(), nullable=False),
    sa.Column('aantal', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint("doel IN ('to keep', 'for sale', 'to be thrown away')", name='CC2'),
    sa.CheckConstraint("verpakking IN ('open', 'gesloten', 'geen')", name='CC3'),
    sa.ForeignKeyConstraint(['materiaal_id'], ['materiaal.materiaal_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['zone'], ['zone.zone'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('materiaal_id', 'zone', 'doel', 'verpakking', name='UC2')
    )
    op.create_table('gebruik',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('gebruiker', sa.String(), nullable=False),
    sa.Column('datum', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('hoeveelheid', sa.Integer(), nullable=False),
    sa.Column('project', sa.String(), nullable=True),
    sa.Column('reservatie', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', 'gebruiker', 'datum')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gebruik')
    op.drop_table('item')
    op.drop_table('materiaal')
    op.drop_table('zone')
    op.drop_table('lifecycle')
    # ### end Alembic commands ###
