#Zoveel mogelijk aangesloten aan cursus Databasesystemen

CREATE TABLE company (
  company_name text NOT NULL PRIMARY KEY
);

CREATE TABLE app_user (
  username text NOT NULL PRIMARY KEY,
  company_name text NOT NULL,
  FOREIGN KEY (company_name) REFERENCES company (company_name)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE material (
  material_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  material_type text NOT NULL,
  description text NOT NULL,
  lifecycle text,
  brand text NOT NULL,
  price numeric,
  company_name  text NOT NULL,
  CONSTRAINT UC1 UNIQUE(company_name, material_type, brand),
  CONSTRAINT CC1 CHECK(price >= 0),
  FOREIGN KEY (company_name) REFERENCES company (company_name)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE zone (
  zone_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  zone_name text NOT NULL,
  company_name text NOT NULL,
  CONSTRAINT UC2 UNIQUE (company_name, zone_name),
  FOREIGN KEY (company_name) REFERENCES company (company_name)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE item (
  item_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  material_id int NOT NULL,
  zone_id int NOT NULL,
  purpose text NOT NULL,
  packaging text NOT NULL,
  quantity int NOT NULL,
  comment text,
  CONSTRAINT UC3 UNIQUE(material_id, zone_id, purpose, packaging),
  CONSTRAINT CC2 CHECK(purpose IN('keep', 'sell', 'dispose')),
  CONSTRAINT CC3 CHECK(packaging IN('open', 'closed', 'none')),
  CONSTRAINT CC4 CHECK(quantity >= 0),
  FOREIGN KEY (material_id) REFERENCES material (material_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (zone_id) REFERENCES zone (zone_id)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE reservation (
  reservation_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  item_id int NOT NULL,
  username text NOT NULL,
  date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  quantity int NOT NULL,
  project text,
  CONSTRAINT CC5 CHECK(quantity > 0),
  FOREIGN KEY (item_id) REFERENCES item (item_id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (username) REFERENCES app_user (username)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE material_event (
  id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  username text NOT NULL,
  material_id int NOT NULL,
  event_type text NOT NULL,
  total_events int NOT NULL DEFAULT 0,
  date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT UC4 UNIQUE(username, material_id, event_type),
  CONSTRAINT CC6 CHECK(event_type IN('view', 'reserve')),
  FOREIGN KEY (username) REFERENCES app_user (username)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (material_id) REFERENCES material (material_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);