CREATE TABLE lifecycle (
  lifecycle text NOT NULL PRIMARY KEY
);

CREATE TABLE materiaal (
  materiaal_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  type text NOT NULL,
  omschrijving text NOT NULL,
  lifecycle text,
  merk text NOT NULL,
  prijs numeric,
  CONSTRAINT UC1 UNIQUE(type, omschrijving),
  FOREIGN KEY (lifecycle) REFERENCES lifecycle (lifecycle)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE zone (
  zone text NOT NULL PRIMARY KEY
);

CREATE TABLE item (
  item_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  materiaal_id int NOT NULL,
  zone text NOT NULL,
  doel text NOT NULL,
  verpakking text NOT NULL,
  aantal int NOT NULL,
  comment text,
  CONSTRAINT UC2 UNIQUE(materiaal_id, zone, doel, verpakking),
  CONSTRAINT CC2 CHECK(doel IN('to keep', 'for sale', 'to be thrown away')),
  CONSTRAINT CC3 CHECK(verpakking IN('open', 'gesloten', 'geen')),
  FOREIGN KEY (materiaal_id) REFERENCES materiaal (materiaal_id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  FOREIGN KEY (zone) REFERENCES zone (zone)
    ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE gebruik (
  item_id int NOT NULL,
  gebruiker text NOT NULL,
  datum timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  hoeveelheid int NOT NULL,
  project text,
  reservatie text,
  PRIMARY KEY (item_id, gebruiker, datum),
  FOREIGN KEY (item_id) REFERENCES item (item_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);