
CREATE TABLE material (
  material_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  material_type text NOT NULL,
  description text NOT NULL,
  lifecycle text,
  brand text NOT NULL,
  price numeric,
  CONSTRAINT UC1 UNIQUE(material_type, description)
);

CREATE TABLE zone (
  zone_name char(3) NOT NULL PRIMARY KEY
);

CREATE TABLE item (
  item_id int GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  material_id int NOT NULL,
  zone_name char(3) NOT NULL,
  purpose text NOT NULL,
  packaging text NOT NULL,
  quantity int NOT NULL,
  comment text,
  CONSTRAINT UC2 UNIQUE(material_id, zone_name, purpose, packaging),
  CONSTRAINT CC2 CHECK(purpose IN('keep', 'sell', 'dispose')),
  CONSTRAINT CC3 CHECK(packaging IN('open', 'closed', 'none')),
  FOREIGN KEY (material_id) REFERENCES material (material_id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (zone_name) REFERENCES zone (zone_name)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE reservation (
  item_id int NOT NULL,
  username text NOT NULL,
  date timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  quantity int NOT NULL,
  project text,
  PRIMARY KEY (item_id, username, date),
  FOREIGN KEY (item_id) REFERENCES item (item_id)
    ON DELETE CASCADE ON UPDATE CASCADE
);